[package]
name = "diff"
version = "0.1.2"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
description = "An LCS based slice and string diffing implementation."
license = "MIT"

[dev-dependencies]
speculate = "0.0.14"
quickcheck = "0.2.16"
